#  **Introduction au Python**
Python est un language de programation interprété, haut niveau. Elle prend en charge plusieurs paradigmes de programmation: procédurale, orientée objet et fonctionnelle. Ce language est largement utilisé dans le domaine de l'intelligence artificielle en raison de sa facilité d utilisation ainsi que ses biblioteques riches  
adaptées à cette discipline tel que `numpy` et `pandas`.

## **0. Imports**

In [1151]:
import numpy as np 
import pandas as pd 

## **1. Syntaxe Python**

Tandis que certains langages de programmation utilisent l'indentation du code uniquement pour améliorer la lisibilité, en Python, elle est essentielle, elle permet d'indiquer un bloc de code.

In [1152]:
# Les commentaires en python commencent par "#" 

print("Pour afficher un texte en python utiliser le mot clé 'print' ")

valeur=4
print("Valeur de la variable =",valeur) # Pour afficher un texte avec une variable

Pour afficher un texte en python utiliser le mot clé 'print' 
Valeur de la variable = 4


### **1.1 Variables**

 Contrairement aux langages à typage statique comme C ou Java, qui nécessitent une déclaration explicite des variables, Python se passe de cette exigence

#### Types de bases

In [1153]:
x = 5 
y = "Hello, World!" 
z= 3.8 
w= True

print(type(x))
print(type(y))
print(type(z))
print(type(w))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'bool'>


#### Assignation

In [1154]:
print(y)
y=x # x=5
print(y)
print(type(y))

Hello, World!
5
<class 'int'>


#### Operations Arithmetiques

In [1155]:
a=2*10-4
print(a)

b=a%3
print(b)

16
1


#### Operations Logiques

In [1156]:
print(a>b)# a=16 b=1
print(a==b)

True
False


### **1.2 Conditions et Boucles**

#### Condition: if..else..

In [1157]:
val1=5
val2=70

if val2>50:
    val1=10
else:
    val1=0
    
print(val1)

10


#### Boucle FOR

 Rappel de la loi du factorielle: **N! = N * (N-1) * (N-2) * (N-3) *...* 1**

In [1158]:
N=5
total=1
for i in range(N):
    total=total*(N-i)
    
print(N,"! =",total)

5 ! = 120


#### Boucle WHILE

In [1159]:
N=5
total=1
i=0
while(i<N):
    total=total*(N-i)
    i+=1

print(N,"! =",total)

5 ! = 120


### **1.3 Fonctions**

Rappel de la loi de la puissance: **X<sup>n</sup> = X * X * X * X * X (n fois)**

In [1160]:
def Puissance(X,n):
    resultat=1
    for _ in range(n):
        resultat=resultat*X
    return resultat 

In [1161]:
x=5
n=2 
print("X^n= ",Puissance(x,n)) 
print(x**n)

X^n=  25
25


### **1.4 Types avancées**

#### Listes

In [1162]:
L1=[9,8,7,6,5]
print(L1)
print("Longueur de L1:",len(L1))

[9, 8, 7, 6, 5]
Longueur de L1: 5


In [1163]:
print(L1[2])
print(L1[-1])
print(L1[1:3])
print(L1[:2])
print(L1[2:])

7
5
[8, 7]
[9, 8]
[7, 6, 5]


In [1164]:
print('Liste de base:', L1)
L1.append(9)
L1.remove(6)
L1[0]=-1
print('Liste modifiée:', L1)

L1.sort()
print('Liste ordonnée:',L1)

print('Nombre de \'9\' est :',L1.count(9))

Liste de base: [9, 8, 7, 6, 5]
Liste modifiée: [-1, 8, 7, 5, 9]
Liste ordonnée: [-1, 5, 7, 8, 9]
Nombre de '9' est : 1


In [1165]:
L2=["c","g","e","a"]
L3=[1.5,25.99,29.0,30.4]

L4=[3,50.4,"truc",True]
print([type(item) for item in L4])

[<class 'int'>, <class 'float'>, <class 'str'>, <class 'bool'>]


In [1166]:
L4=list((0,-11,2,3))
L4

[0, -11, 2, 3]

In [1167]:
print("L1 = ",L1,"L4 = ",L4)
print("L1+L4 = ",L1+L4)# concatenation de L1 et L4 
print("L4*2 = ",L4*2)# equivalent de L4+L4 (concatenation)

L1 =  [-1, 5, 7, 8, 9] L4 =  [0, -11, 2, 3]
L1+L4 =  [-1, 5, 7, 8, 9, 0, -11, 2, 3]
L4*2 =  [0, -11, 2, 3, 0, -11, 2, 3]


#### Dictionaires

In [1168]:
personne = {
    'nom': 'Fatima',
    'age': 25,
    'ville': 'Caire'
}
personne

{'nom': 'Fatima', 'age': 25, 'ville': 'Caire'}

In [1169]:
personne.keys()

dict_keys(['nom', 'age', 'ville'])

In [1170]:
personne.values()

dict_values(['Fatima', 25, 'Caire'])

In [1171]:
personne['age'] = 26  # modification d'une valeur
personne['job'] = 'Engenieur'  # ajout d'un item
print(personne)

{'nom': 'Fatima', 'age': 26, 'ville': 'Caire', 'job': 'Engenieur'}


## **2. NumPy**

`NumPy` (Numerical Python) est une bibliothèque Python open source largement utilisée dans le calcul scientifique et numérique. Elle offre une prise en charge des  
tableaux et matrices multidimensionnels de grande taille, ainsi qu'une vaste collection de fonctions mathématiques de haut niveau pour manipuler efficacement ces tableaux.

In [1172]:
A = np.array([1,2,3]) #tableau a une dimension
B = np.array([(2,1.5,3), (5,4,6)]) # tableau a 2 dimension
C = np.array([[(1,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float) # tableau a 3 dimensions avec type float explicitement donné 

print("A=",A)
print("\nB=\n",B)
print("\nC=\n",C)

A= [1 2 3]

B=
 [[2.  1.5 3. ]
 [5.  4.  6. ]]

C=
 [[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]


In [1173]:
print("Dimensions de C:",C.shape)# (x,y,z)
print("\nLongueur de C:",len(C))# Nombre d'element du la premiere dimension
print("\nNombre de dimensions de C:",C.ndim)
print("\nTaille de C:",C.size)# Nombre d'elements
print("\nType de C:",C.dtype)
C.astype(int)# convertion de type

Dimensions de C: (2, 2, 3)

Longueur de C: 2

Nombre de dimensions de C: 3

Taille de C: 12

Type de C: float64


array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [4, 5, 6]]])

In [1174]:
print("Matrice de 0:\n",np.zeros((1,3)))
print("\nMatrice de 1:\n",np.ones((2,3),dtype=np.int16))
print("\nMatrice d'une meme valeur:\n",np.full((2,2),7))

Matrice de 0:
 [[0. 0. 0.]]

Matrice de 1:
 [[1 1 1]
 [1 1 1]]

Matrice d'une meme valeur:
 [[7 7]
 [7 7]]


In [1175]:
D=np.arange(10,25,5)
print("Matrice de valeurs espacées uniformément:\n",D)
print("\nMatrice d'identité:\n",np.eye(2))
print("\nMatrice à valeurs aléatoires:\n",np.random.random((2,2)))

Matrice de valeurs espacées uniformément:
 [10 15 20]

Matrice d'identité:
 [[1. 0.]
 [0. 1.]]

Matrice à valeurs aléatoires:
 [[0.5913231  0.41289296]
 [0.29825838 0.03277152]]


#### Operations Arithmetiques et Logiques

In [1176]:
print("Rappel B=\n",B)
print("\nRappel A=",A)
print("\n2 x A:",2*A)
print("\ne^A:\n",np.exp(A))
print("\nracine(A):\n",np.sqrt(A))
print("\nA+B:\n",np.add(A,B))
print("\nA-B:\n",A-B)

Rappel B=
 [[2.  1.5 3. ]
 [5.  4.  6. ]]

Rappel A= [1 2 3]

2 x A: [2 4 6]

e^A:
 [ 2.71828183  7.3890561  20.08553692]

racine(A):
 [1.         1.41421356 1.73205081]

A+B:
 [[3.  3.5 6. ]
 [6.  6.  9. ]]

A-B:
 [[-1.   0.5  0. ]
 [-4.  -2.  -3. ]]


In [1177]:
print("A==B:\n",A==B)
print("\nA>2:\n",A>2)

A==B:
 [[False False  True]
 [False False False]]

A>2:
 [False False  True]


In [1178]:
A,B,C

(array([1, 2, 3]),
 array([[2. , 1.5, 3. ],
        [5. , 4. , 6. ]]),
 array([[[1., 2., 3.],
         [4., 5., 6.]],
 
        [[3., 2., 1.],
         [4., 5., 6.]]]))

In [1179]:
A.sum(), A.max(axis=0), A.mean(), np.median(A) #fonctions d'aggregation

(np.int64(6), np.int64(3), np.float64(2.0), np.float64(2.0))

In [1180]:
print(C[0:2,:2,1:],"\n") 
print(B[B>=4])# element de B qui sont >=4

[[[2. 3.]
  [5. 6.]]

 [[2. 1.]
  [5. 6.]]] 

[5. 4. 6.]


In [1181]:
print("Matrice B:\n",B)
B.sort()
print("\nMatrice B ordonnée:\n",B)
print("\nMatrice B tranposé:\n",B.T)
print("\nMatrice B remodelé:\n",B.reshape(1,6))

Matrice B:
 [[2.  1.5 3. ]
 [5.  4.  6. ]]

Matrice B ordonnée:
 [[1.5 2.  3. ]
 [4.  5.  6. ]]

Matrice B tranposé:
 [[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]

Matrice B remodelé:
 [[1.5 2.  3.  4.  5.  6. ]]


In [1182]:
A,B,D

(array([1, 2, 3]),
 array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]),
 array([10, 15, 20]))

In [1183]:
np.append(A,B),np.insert(A, 1, 5),np.delete(A,0) #ajout, insertion de 5 à l'indice 1  et suppression de l'eleement à l'indice 0

(array([1. , 2. , 3. , 1.5, 2. , 3. , 4. , 5. , 6. ]),
 array([1, 5, 2, 3]),
 array([2, 3]))

In [1184]:
np.concatenate((A,D)),np.vstack((A,D)),np.vsplit(B,2) # concatenation,empilement verticale (il existe aussi horizontalement) 
# et une separation verticale en 2 sous tableaux de meme taille

(array([ 1,  2,  3, 10, 15, 20]),
 array([[ 1,  2,  3],
        [10, 15, 20]]),
 [array([[1.5, 2. , 3. ]]), array([[4., 5., 6.]])])

Ces fonctions de modifient pas le tableau original mais agissent sur une copie. Pour modifier le tableau original il faut lui assigner le resultat de l'operation

In [1185]:
print(A)
A=np.concatenate((A,D))
print(A)

[1 2 3]
[ 1  2  3 10 15 20]


## **3. Pandas**

`Pandas` est une bibliothèque open-source de Python utilisée pour la manipulation et l'analyse de données. Elle fournit des structures de données puissantes, comme les ``DataFrame`` et les ``Series``.
Les ``Series`` est une structure de données unidimensionnelle avec des indices associés pour acceder aux valeurs, tandis que le ``DataFrame`` est un tableau bidimensionnelle ou Chaque colonne est une ``Series``, avec une étiquette pour chaque colonne, la rendant adapté aux jeux de données tabulaires.

### **3.1 Pandas Series Object**

In [1186]:
s = pd.Series([3, -5, 7, 4], index=['a', 'b', 'c', 'd'])
s

a    3
b   -5
c    7
d    4
dtype: int64

#### Accès aux éléments

In [1187]:
print(s['a'])
print(s[(s < 1)])

3
b   -5
dtype: int64


#### Modification d'éléments

In [1188]:
print(s['a'])
s['a'] = 6
print(s['a'])

3
6


#### Ajout d' éléments

In [1189]:
s3 = pd.Series([7, -2, 3], index=[ 'a', 'c','d' ])
s,s3

(a    6
 b   -5
 c    7
 d    4
 dtype: int64,
 a    7
 c   -2
 d    3
 dtype: int64)

In [1190]:
print(s+s3)
print(s.add(s3,fill_value=0))# remplit par 0 les valeurs manquantes avant d'ajouter (il manque l element "b" à s3 )

a    13.0
b     NaN
c     5.0
d     7.0
dtype: float64
a    13.0
b    -5.0
c     5.0
d     7.0
dtype: float64


#### Suppression d' éléments

In [1191]:
s.drop(index=['a' ,'c' ])#supprimer des elements

b   -5
d    4
dtype: int64

### **3.2 Pandas DataFrame**

In [1192]:
data = {
    'Country' :['Belgium', 'India', 'Brazil'],
    'Capital':['Brussels', 'New Delhi', 'Brasília'],
    'population': [11190846, 1303171035, 207847528]
}
df = pd.DataFrame(data)
df

Country    Capital  population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasília   207847528

In [1193]:
print(df.shape)#(lignes,colonnes)
print(df.index) #Description des indices
print(df.columns) #Description des colonnes
print(df.count()) #Nombre de valeurs non null

(3, 3)
RangeIndex(start=0, stop=3, step=1)
Index(['Country', 'Capital', 'population'], dtype='object')
Country       3
Capital       3
population    3
dtype: int64


In [1194]:
df.info() #Info sur DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Country     3 non-null      object
 1   Capital     3 non-null      object
 2   population  3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [1195]:
df.describe() #résumé des statistiques

population
count  3.000000e+00
mean   5.074031e+08
std    6.961346e+08
min    1.119085e+07
25%    1.095192e+08
50%    2.078475e+08
75%    7.555093e+08
max    1.303171e+09

#### Acès aux éléments

In [1196]:
print(df.iloc[[0],[0]])# acces par indice
print("\n",df.loc[[0], ['Country' ]])# acces par etiquette
print("\n",df[1:])

   Country
0  Belgium

    Country
0  Belgium

   Country    Capital  population
1   India  New Delhi  1303171035
2  Brazil   Brasília   207847528


#### Modification d'éléments

In [1197]:
df.rename(columns={"population":"Population"}, inplace=True)
df

Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasília   207847528

In [1198]:
df['Population']=df['Population']%100
df

Country    Capital  Population
0  Belgium   Brussels          46
1    India  New Delhi          35
2   Brazil   Brasília          28

In [1204]:
df=df.sort_values(by='Capital' )
df

Country    Capital  Population
2   Brazil   Brasília          28
0  Belgium   Brussels          46
1    India  New Delhi          35

#### Ajout d'éléments

In [1149]:
df2=pd.DataFrame({"Richness_score":np.random.randint(0,100, len(df))})
df3=pd.concat([df,df2],axis=1)
df3

Country    Capital  Population  Richness_score
0  Belgium   Brussels          46              83
1    India  New Delhi          35               7
2   Brazil   Brasília          28              28

In [1150]:
df['Temperature']= np.random.randint(10, 40, df.shape[0])
df

Country    Capital  Population  Temperature
0  Belgium   Brussels          46           36
1    India  New Delhi          35           25
2   Brazil   Brasília          28           33

#### Suppression d'éléments

La fonction `drop` supprime dans un copie du dataframe tandis que `del` supprime au niveau du dataframe originale

In [651]:
df2=df.drop(0 , axis=0)
print(df2)

  Country    Capital  Population
1   India  New Delhi  1303171035
2  Brazil   Brasília   207847528


In [602]:
del df['Capital']
df

Country  Population
0  Belgium    11190846
1    India  1303171035
2   Brazil   207847528